import type { RentalItem, RentalReceipt } from "./types";

const DEMO_NOW = 1778284800000;
export const DEMO_OWNER_WALLET = "3z6edmobZbGBQP1pxfYi3XuxqEFeZn1rZfGBegtJ2GAh";

export const COMMUNITY_ITEMS: RentalItem[] = [
  {
    id: "power_bank_18",
    name: "Power Bank #18",
    brand: "Anker",
    model: "20K USB-C",
    condition: 9,
    description: "High-capacity power bank with USB-C cable. Best for a full hackathon work session.",
    imageUrl: "https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=900&h=700&fit=crop",
    ratePerHour: 2,
    minimumFee: 3,
    buyoutCap: 30,
    expectedHours: 3,
    status: "available",
    owner: DEMO_OWNER_WALLET,
    ownerName: "Dev Hub Desk",
    locationLabel: "Main hall, table B",
    category: "Power",
    ownerScore: 96,
    returnedOkCount: 41,
    autoBuyoutCount: 3,
    disputeCount: 0,
    createdAt: DEMO_NOW - 86400000,
  },
  {
    id: "charger_07",
    name: "USB-C Charger #07",
    brand: "Apple",
    model: "67W USB-C",
    condition: 8,
    description: "Compact wall charger with one USB-C cable. Good for laptops and phones.",
    imageUrl: "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=900&h=700&fit=crop",
    ratePerHour: 1,
    minimumFee: 2,
    buyoutCap: 20,
    expectedHours: 4,
    status: "available",
    owner: DEMO_OWNER_WALLET,
    ownerName: "Nina",
    locationLabel: "Workshop room",
    category: "Power",
    ownerScore: 94,
    returnedOkCount: 28,
    autoBuyoutCount: 1,
    disputeCount: 0,
    createdAt: DEMO_NOW - 86400000 * 2,
  },
  {
    id: "adapter_03",
    name: "HDMI Adapter #03",
    brand: "Belkin",
    model: "USB-C to HDMI",
    condition: 8,
    description: "USB-C HDMI adapter for demo screens and projectors.",
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=900&h=700&fit=crop",
    ratePerHour: 1,
    minimumFee: 2,
    buyoutCap: 15,
    expectedHours: 2,
    status: "available",
    owner: DEMO_OWNER_WALLET,
    ownerName: "A/V Station",
    locationLabel: "Demo stage",
    category: "Adapters",
    ownerScore: 91,
    returnedOkCount: 19,
    autoBuyoutCount: 2,
    disputeCount: 1,
    createdAt: DEMO_NOW - 86400000 * 3,
  },
  {
    id: "umbrella_02",
    name: "Umbrella #02",
    brand: "Totes",
    model: "Compact",
    condition: 7,
    description: "Compact umbrella for a quick walk between venues.",
    imageUrl: "https://images.unsplash.com/photo-1518173946687-a4c8892bbd9f?w=900&h=700&fit=crop",
    ratePerHour: 0.5,
    minimumFee: 1,
    buyoutCap: 12,
    expectedHours: 2,
    status: "rented",
    owner: DEMO_OWNER_WALLET,
    ownerName: "Community Desk",
    locationLabel: "Entrance desk",
    renter: "6rP3...User",
    rentalStart: DEMO_NOW - 1000 * 60 * 48,
    rentalHours: 2,
    category: "Weather",
    ownerScore: 89,
    returnedOkCount: 33,
    autoBuyoutCount: 4,
    disputeCount: 1,
    createdAt: DEMO_NOW - 86400000 * 4,
  },
  {
    id: "mic_11",
    name: "Wireless Mic #11",
    brand: "Rode",
    model: "Wireless GO",
    condition: 9,
    description: "Two-channel wireless mic kit for interviews, demos, and recorded walkthroughs.",
    imageUrl: "https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=900&h=700&fit=crop",
    ratePerHour: 3,
    minimumFee: 6,
    buyoutCap: 70,
    expectedHours: 2,
    status: "available",
    owner: DEMO_OWNER_WALLET,
    ownerName: "Creator Booth",
    locationLabel: "Media table",
    category: "Audio",
    ownerScore: 97,
    returnedOkCount: 52,
    autoBuyoutCount: 1,
    disputeCount: 0,
    createdAt: DEMO_NOW - 86400000 * 5,
  },
  {
    id: "camera_04",
    name: "Mirrorless Camera #04",
    brand: "Sony",
    model: "A6400",
    condition: 8,
    description: "Compact camera body with 16-50 lens for product shots and pitch videos.",
    imageUrl: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=900&h=700&fit=crop",
    ratePerHour: 8,
    minimumFee: 16,
    buyoutCap: 420,
    expectedHours: 2,
    status: "available",
    owner: DEMO_OWNER_WALLET,
    ownerName: "Photo Desk",
    locationLabel: "Studio corner",
    category: "Video",
    ownerScore: 93,
    returnedOkCount: 22,
    autoBuyoutCount: 0,
    disputeCount: 1,
    createdAt: DEMO_NOW - 86400000 * 6,
  },
  {
    id: "tripod_09",
    name: "Tripod #09",
    brand: "Manfrotto",
    model: "Compact Action",
    condition: 8,
    description: "Lightweight tripod for demo recording and overhead product footage.",
    imageUrl: "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=900&h=700&fit=crop",
    ratePerHour: 1,
    minimumFee: 3,
    buyoutCap: 45,
    expectedHours: 3,
    status: "available",
    owner: DEMO_OWNER_WALLET,
    ownerName: "A/V Station",
    locationLabel: "Demo stage",
    category: "Video",
    ownerScore: 92,
    returnedOkCount: 31,
    autoBuyoutCount: 1,
    disputeCount: 0,
    createdAt: DEMO_NOW - 86400000 * 7,
  },
  {
    id: "keyboard_15",
    name: "Keyboard #15",
    brand: "Logitech",
    model: "MX Keys Mini",
    condition: 9,
    description: "Quiet Bluetooth keyboard for temporary workstation setups.",
    imageUrl: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=900&h=700&fit=crop",
    ratePerHour: 1,
    minimumFee: 2,
    buyoutCap: 55,
    expectedHours: 4,
    status: "available",
    owner: DEMO_OWNER_WALLET,
    ownerName: "Ops Desk",
    locationLabel: "Check-in counter",
    category: "Workspace",
    ownerScore: 95,
    returnedOkCount: 44,
    autoBuyoutCount: 1,
    disputeCount: 0,
    createdAt: DEMO_NOW - 86400000 * 8,
  },
  {
    id: "monitor_22",
    name: "Portable Monitor #22",
    brand: "ASUS",
    model: "ZenScreen",
    condition: 8,
    description: "USB-C portable display for pair programming and live dashboard demos.",
    imageUrl: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=900&h=700&fit=crop",
    ratePerHour: 4,
    minimumFee: 8,
    buyoutCap: 180,
    expectedHours: 3,
    status: "available",
    owner: DEMO_OWNER_WALLET,
    ownerName: "Dev Hub Desk",
    locationLabel: "Main hall, table C",
    category: "Workspace",
    ownerScore: 90,
    returnedOkCount: 17,
    autoBuyoutCount: 2,
    disputeCount: 1,
    createdAt: DEMO_NOW - 86400000 * 9,
  },
  {
    id: "badge_printer_01",
    name: "Label Printer #01",
    brand: "Brother",
    model: "QL-800",
    condition: 7,
    description: "Thermal label printer for booth badges, item tags, and pickup receipts.",
    imageUrl: "https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?w=900&h=700&fit=crop",
    ratePerHour: 2,
    minimumFee: 5,
    buyoutCap: 120,
    expectedHours: 2,
    status: "return_requested",
    owner: DEMO_OWNER_WALLET,
    ownerName: "Registration",
    locationLabel: "Front desk",
    category: "Workspace",
    ownerScore: 88,
    returnedOkCount: 15,
    autoBuyoutCount: 3,
    disputeCount: 1,
    createdAt: DEMO_NOW - 86400000 * 10,
  },
  {
    id: "router_06",
    name: "Travel Router #06",
    brand: "GL.iNet",
    model: "Beryl AX",
    condition: 8,
    description: "Portable Wi-Fi router for booths that need a stable private network.",
    imageUrl: "https://images.unsplash.com/photo-1606904825846-647eb07f5be2?w=900&h=700&fit=crop",
    ratePerHour: 2,
    minimumFee: 4,
    buyoutCap: 90,
    expectedHours: 4,
    status: "available",
    owner: DEMO_OWNER_WALLET,
    ownerName: "Infra Table",
    locationLabel: "Back office",
    category: "Connectivity",
    ownerScore: 94,
    returnedOkCount: 26,
    autoBuyoutCount: 1,
    disputeCount: 0,
    createdAt: DEMO_NOW - 86400000 * 11,
  },
  {
    id: "projector_13",
    name: "Mini Projector #13",
    brand: "Anker",
    model: "Nebula Capsule",
    condition: 8,
    description: "Battery-powered projector for breakout rooms and tabletop demos.",
    imageUrl: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=900&h=700&fit=crop",
    ratePerHour: 5,
    minimumFee: 10,
    buyoutCap: 240,
    expectedHours: 2,
    status: "available",
    owner: DEMO_OWNER_WALLET,
    ownerName: "Demo Desk",
    locationLabel: "Breakout room",
    category: "Video",
    ownerScore: 91,
    returnedOkCount: 18,
    autoBuyoutCount: 2,
    disputeCount: 0,
    createdAt: DEMO_NOW - 86400000 * 12,
  },
];

let items = [...COMMUNITY_ITEMS];

export function getItems(): RentalItem[] {
  return items;
}

export function getItem(id: string): RentalItem | undefined {
  return items.find((item) => item.id === id);
}

export function startRental(id: string, renter: string, hours: number): RentalItem | undefined {
  const now = Date.now();
  let updated: RentalItem | undefined;
  items = items.map((item) => {
    if (item.id !== id) return item;
    updated = {
      ...item,
      status: "rented",
      renter,
      rentalStart: now,
      rentalHours: hours,
    };
    return updated;
  });
  return updated;
}

export function requestReturn(id: string): RentalItem | undefined {
  let updated: RentalItem | undefined;
  items = items.map((item) => {
    if (item.id !== id) return item;
    updated = { ...item, status: "return_requested" };
    return updated;
  });
  return updated;
}

export function createReturnedReceipt(item: RentalItem): RentalReceipt {
  const hours = item.rentalStart ? Math.max(1, Math.ceil((Date.now() - item.rentalStart) / 3600000)) : item.expectedHours;
  const grossFee = Math.min(Math.max(item.minimumFee, hours * item.ratePerHour), item.buyoutCap);
  const platformFee = Number((grossFee * 0.05).toFixed(2));
  return {
    id: `receipt_${crypto.randomUUID().slice(0, 8)}`,
    sessionId: `session_${item.id}`,
    itemId: item.id,
    outcome: "returned_ok",
    grossFee,
    platformFee,
    ownerPayout: Number((grossFee - platformFee).toFixed(2)),
    renterRefund: Number((item.buyoutCap - grossFee).toFixed(2)),
    rentalTokenStatus: "burned",
    createdAt: Date.now(),
  };
}
