[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
rental_session = "AVL316tYxrg8MhEeWtaxbwdShMWybzRAH1zNQWvX355K"

[programs.devnet]
rental_session = "AVL316tYxrg8MhEeWtaxbwdShMWybzRAH1zNQWvX355K"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npm run test:anchor"
